/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MDS */

#ifndef _Included_MDS
#define _Included_MDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MDS
 * Method:    isPrevInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_MDS_isPrevInstance
  (JNIEnv *, jobject);

/*
 * Class:     MDS
 * Method:    terminatWinExplorer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_MDS_setHighPriorityClass
  (JNIEnv *, jobject);

/*
 * Class:     MDS
 * Method:    getValidationCode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MDS_getValidationCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
