/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemMouseEvent */

#ifndef _Included_SystemMouseEvent
#define _Included_SystemMouseEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef SystemMouseEvent_ALT_DOWN_MASK
#define SystemMouseEvent_ALT_DOWN_MASK 512L
#undef SystemMouseEvent_ALT_GRAPH_DOWN_MASK
#define SystemMouseEvent_ALT_GRAPH_DOWN_MASK 8192L
#undef SystemMouseEvent_ALT_GRAPH_MASK
#define SystemMouseEvent_ALT_GRAPH_MASK 32L
#undef SystemMouseEvent_ALT_MASK
#define SystemMouseEvent_ALT_MASK 8L
#undef SystemMouseEvent_BUTTON1_DOWN_MASK
#define SystemMouseEvent_BUTTON1_DOWN_MASK 1024L
#undef SystemMouseEvent_BUTTON1_MASK
#define SystemMouseEvent_BUTTON1_MASK 16L
#undef SystemMouseEvent_BUTTON2_DOWN_MASK
#define SystemMouseEvent_BUTTON2_DOWN_MASK 2048L
#undef SystemMouseEvent_BUTTON2_MASK
#define SystemMouseEvent_BUTTON2_MASK 8L
#undef SystemMouseEvent_BUTTON3_DOWN_MASK
#define SystemMouseEvent_BUTTON3_DOWN_MASK 4096L
#undef SystemMouseEvent_BUTTON3_MASK
#define SystemMouseEvent_BUTTON3_MASK 4L
#undef SystemMouseEvent_CTRL_DOWN_MASK
#define SystemMouseEvent_CTRL_DOWN_MASK 128L
#undef SystemMouseEvent_CTRL_MASK
#define SystemMouseEvent_CTRL_MASK 2L
#undef SystemMouseEvent_META_DOWN_MASK
#define SystemMouseEvent_META_DOWN_MASK 256L
#undef SystemMouseEvent_META_MASK
#define SystemMouseEvent_META_MASK 4L
#undef SystemMouseEvent_SHIFT_DOWN_MASK
#define SystemMouseEvent_SHIFT_DOWN_MASK 64L
#undef SystemMouseEvent_SHIFT_MASK
#define SystemMouseEvent_SHIFT_MASK 1L
#undef SystemMouseEvent_BUTTON1
#define SystemMouseEvent_BUTTON1 1L
#undef SystemMouseEvent_BUTTON2
#define SystemMouseEvent_BUTTON2 2L
#undef SystemMouseEvent_BUTTON3
#define SystemMouseEvent_BUTTON3 3L
#undef SystemMouseEvent_NOBUTTON
#define SystemMouseEvent_NOBUTTON 0L
#ifdef __cplusplus
}
#endif
#endif
