/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemInfo */

#ifndef _Included_SystemInfo
#define _Included_SystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemInfo
 * Method:    ProcessorLoadPercentage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SystemInfo_ProcessorLoadPercentage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
