/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemKeyEvent */

#ifndef _Included_SystemKeyEvent
#define _Included_SystemKeyEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef SystemKeyEvent_ALT_DOWN_MASK
#define SystemKeyEvent_ALT_DOWN_MASK 512L
#undef SystemKeyEvent_ALT_GRAPH_DOWN_MASK
#define SystemKeyEvent_ALT_GRAPH_DOWN_MASK 8192L
#undef SystemKeyEvent_ALT_GRAPH_MASK
#define SystemKeyEvent_ALT_GRAPH_MASK 32L
#undef SystemKeyEvent_ALT_MASK
#define SystemKeyEvent_ALT_MASK 8L
#undef SystemKeyEvent_BUTTON1_DOWN_MASK
#define SystemKeyEvent_BUTTON1_DOWN_MASK 1024L
#undef SystemKeyEvent_BUTTON1_MASK
#define SystemKeyEvent_BUTTON1_MASK 16L
#undef SystemKeyEvent_BUTTON2_DOWN_MASK
#define SystemKeyEvent_BUTTON2_DOWN_MASK 2048L
#undef SystemKeyEvent_BUTTON2_MASK
#define SystemKeyEvent_BUTTON2_MASK 8L
#undef SystemKeyEvent_BUTTON3_DOWN_MASK
#define SystemKeyEvent_BUTTON3_DOWN_MASK 4096L
#undef SystemKeyEvent_BUTTON3_MASK
#define SystemKeyEvent_BUTTON3_MASK 4L
#undef SystemKeyEvent_CTRL_DOWN_MASK
#define SystemKeyEvent_CTRL_DOWN_MASK 128L
#undef SystemKeyEvent_CTRL_MASK
#define SystemKeyEvent_CTRL_MASK 2L
#undef SystemKeyEvent_META_DOWN_MASK
#define SystemKeyEvent_META_DOWN_MASK 256L
#undef SystemKeyEvent_META_MASK
#define SystemKeyEvent_META_MASK 4L
#undef SystemKeyEvent_SHIFT_DOWN_MASK
#define SystemKeyEvent_SHIFT_DOWN_MASK 64L
#undef SystemKeyEvent_SHIFT_MASK
#define SystemKeyEvent_SHIFT_MASK 1L
#undef SystemKeyEvent_CHAR_UNDEFINED
#define SystemKeyEvent_CHAR_UNDEFINED 65535L
#undef SystemKeyEvent_KEY_FIRST
#define SystemKeyEvent_KEY_FIRST 400L
#undef SystemKeyEvent_KEY_LAST
#define SystemKeyEvent_KEY_LAST 402L
#undef SystemKeyEvent_KEY_LOCATION_LEFT
#define SystemKeyEvent_KEY_LOCATION_LEFT 2L
#undef SystemKeyEvent_KEY_LOCATION_NUMPAD
#define SystemKeyEvent_KEY_LOCATION_NUMPAD 4L
#undef SystemKeyEvent_KEY_LOCATION_RIGHT
#define SystemKeyEvent_KEY_LOCATION_RIGHT 3L
#undef SystemKeyEvent_KEY_LOCATION_STANDARD
#define SystemKeyEvent_KEY_LOCATION_STANDARD 1L
#undef SystemKeyEvent_KEY_LOCATION_UNKNOWN
#define SystemKeyEvent_KEY_LOCATION_UNKNOWN 0L
#undef SystemKeyEvent_KEY_PRESSED
#define SystemKeyEvent_KEY_PRESSED 401L
#undef SystemKeyEvent_KEY_RELEASED
#define SystemKeyEvent_KEY_RELEASED 402L
#undef SystemKeyEvent_KEY_TYPED
#define SystemKeyEvent_KEY_TYPED 400L
#undef SystemKeyEvent_VK_0
#define SystemKeyEvent_VK_0 48L
#undef SystemKeyEvent_VK_1
#define SystemKeyEvent_VK_1 49L
#undef SystemKeyEvent_VK_2
#define SystemKeyEvent_VK_2 50L
#undef SystemKeyEvent_VK_3
#define SystemKeyEvent_VK_3 51L
#undef SystemKeyEvent_VK_4
#define SystemKeyEvent_VK_4 52L
#undef SystemKeyEvent_VK_5
#define SystemKeyEvent_VK_5 53L
#undef SystemKeyEvent_VK_6
#define SystemKeyEvent_VK_6 54L
#undef SystemKeyEvent_VK_7
#define SystemKeyEvent_VK_7 55L
#undef SystemKeyEvent_VK_8
#define SystemKeyEvent_VK_8 56L
#undef SystemKeyEvent_VK_9
#define SystemKeyEvent_VK_9 57L
#undef SystemKeyEvent_VK_A
#define SystemKeyEvent_VK_A 65L
#undef SystemKeyEvent_VK_ACCEPT
#define SystemKeyEvent_VK_ACCEPT 30L
#undef SystemKeyEvent_VK_ADD
#define SystemKeyEvent_VK_ADD 107L
#undef SystemKeyEvent_VK_AGAIN
#define SystemKeyEvent_VK_AGAIN 65481L
#undef SystemKeyEvent_VK_ALL_CANDIDATES
#define SystemKeyEvent_VK_ALL_CANDIDATES 256L
#undef SystemKeyEvent_VK_ALPHANUMERIC
#define SystemKeyEvent_VK_ALPHANUMERIC 240L
#undef SystemKeyEvent_VK_ALT
#define SystemKeyEvent_VK_ALT 18L
#undef SystemKeyEvent_VK_ALT_GRAPH
#define SystemKeyEvent_VK_ALT_GRAPH 65406L
#undef SystemKeyEvent_VK_AMPERSAND
#define SystemKeyEvent_VK_AMPERSAND 150L
#undef SystemKeyEvent_VK_ASTERISK
#define SystemKeyEvent_VK_ASTERISK 151L
#undef SystemKeyEvent_VK_AT
#define SystemKeyEvent_VK_AT 512L
#undef SystemKeyEvent_VK_B
#define SystemKeyEvent_VK_B 66L
#undef SystemKeyEvent_VK_BACK_QUOTE
#define SystemKeyEvent_VK_BACK_QUOTE 192L
#undef SystemKeyEvent_VK_BACK_SLASH
#define SystemKeyEvent_VK_BACK_SLASH 92L
#undef SystemKeyEvent_VK_BACK_SPACE
#define SystemKeyEvent_VK_BACK_SPACE 8L
#undef SystemKeyEvent_VK_BEGIN
#define SystemKeyEvent_VK_BEGIN 65368L
#undef SystemKeyEvent_VK_BRACELEFT
#define SystemKeyEvent_VK_BRACELEFT 161L
#undef SystemKeyEvent_VK_BRACERIGHT
#define SystemKeyEvent_VK_BRACERIGHT 162L
#undef SystemKeyEvent_VK_C
#define SystemKeyEvent_VK_C 67L
#undef SystemKeyEvent_VK_CANCEL
#define SystemKeyEvent_VK_CANCEL 3L
#undef SystemKeyEvent_VK_CAPS_LOCK
#define SystemKeyEvent_VK_CAPS_LOCK 20L
#undef SystemKeyEvent_VK_CIRCUMFLEX
#define SystemKeyEvent_VK_CIRCUMFLEX 514L
#undef SystemKeyEvent_VK_CLEAR
#define SystemKeyEvent_VK_CLEAR 12L
#undef SystemKeyEvent_VK_CLOSE_BRACKET
#define SystemKeyEvent_VK_CLOSE_BRACKET 93L
#undef SystemKeyEvent_VK_CODE_INPUT
#define SystemKeyEvent_VK_CODE_INPUT 258L
#undef SystemKeyEvent_VK_COLON
#define SystemKeyEvent_VK_COLON 513L
#undef SystemKeyEvent_VK_COMMA
#define SystemKeyEvent_VK_COMMA 44L
#undef SystemKeyEvent_VK_COMPOSE
#define SystemKeyEvent_VK_COMPOSE 65312L
#undef SystemKeyEvent_VK_CONTEXT_MENU
#define SystemKeyEvent_VK_CONTEXT_MENU 525L
#undef SystemKeyEvent_VK_CONTROL
#define SystemKeyEvent_VK_CONTROL 17L
#undef SystemKeyEvent_VK_CONVERT
#define SystemKeyEvent_VK_CONVERT 28L
#undef SystemKeyEvent_VK_COPY
#define SystemKeyEvent_VK_COPY 65485L
#undef SystemKeyEvent_VK_CUT
#define SystemKeyEvent_VK_CUT 65489L
#undef SystemKeyEvent_VK_D
#define SystemKeyEvent_VK_D 68L
#undef SystemKeyEvent_VK_DEAD_ABOVEDOT
#define SystemKeyEvent_VK_DEAD_ABOVEDOT 134L
#undef SystemKeyEvent_VK_DEAD_ABOVERING
#define SystemKeyEvent_VK_DEAD_ABOVERING 136L
#undef SystemKeyEvent_VK_DEAD_ACUTE
#define SystemKeyEvent_VK_DEAD_ACUTE 129L
#undef SystemKeyEvent_VK_DEAD_BREVE
#define SystemKeyEvent_VK_DEAD_BREVE 133L
#undef SystemKeyEvent_VK_DEAD_CARON
#define SystemKeyEvent_VK_DEAD_CARON 138L
#undef SystemKeyEvent_VK_DEAD_CEDILLA
#define SystemKeyEvent_VK_DEAD_CEDILLA 139L
#undef SystemKeyEvent_VK_DEAD_CIRCUMFLEX
#define SystemKeyEvent_VK_DEAD_CIRCUMFLEX 130L
#undef SystemKeyEvent_VK_DEAD_DIAERESIS
#define SystemKeyEvent_VK_DEAD_DIAERESIS 135L
#undef SystemKeyEvent_VK_DEAD_DOUBLEACUTE
#define SystemKeyEvent_VK_DEAD_DOUBLEACUTE 137L
#undef SystemKeyEvent_VK_DEAD_GRAVE
#define SystemKeyEvent_VK_DEAD_GRAVE 128L
#undef SystemKeyEvent_VK_DEAD_IOTA
#define SystemKeyEvent_VK_DEAD_IOTA 141L
#undef SystemKeyEvent_VK_DEAD_MACRON
#define SystemKeyEvent_VK_DEAD_MACRON 132L
#undef SystemKeyEvent_VK_DEAD_OGONEK
#define SystemKeyEvent_VK_DEAD_OGONEK 140L
#undef SystemKeyEvent_VK_DEAD_SEMIVOICED_SOUND
#define SystemKeyEvent_VK_DEAD_SEMIVOICED_SOUND 143L
#undef SystemKeyEvent_VK_DEAD_TILDE
#define SystemKeyEvent_VK_DEAD_TILDE 131L
#undef SystemKeyEvent_VK_DEAD_VOICED_SOUND
#define SystemKeyEvent_VK_DEAD_VOICED_SOUND 142L
#undef SystemKeyEvent_VK_DECIMAL
#define SystemKeyEvent_VK_DECIMAL 110L
#undef SystemKeyEvent_VK_DELETE
#define SystemKeyEvent_VK_DELETE 127L
#undef SystemKeyEvent_VK_DIVIDE
#define SystemKeyEvent_VK_DIVIDE 111L
#undef SystemKeyEvent_VK_DOLLAR
#define SystemKeyEvent_VK_DOLLAR 515L
#undef SystemKeyEvent_VK_DOWN
#define SystemKeyEvent_VK_DOWN 40L
#undef SystemKeyEvent_VK_E
#define SystemKeyEvent_VK_E 69L
#undef SystemKeyEvent_VK_END
#define SystemKeyEvent_VK_END 35L
#undef SystemKeyEvent_VK_ENTER
#define SystemKeyEvent_VK_ENTER 10L
#undef SystemKeyEvent_VK_EQUALS
#define SystemKeyEvent_VK_EQUALS 61L
#undef SystemKeyEvent_VK_ESCAPE
#define SystemKeyEvent_VK_ESCAPE 27L
#undef SystemKeyEvent_VK_EURO_SIGN
#define SystemKeyEvent_VK_EURO_SIGN 516L
#undef SystemKeyEvent_VK_EXCLAMATION_MARK
#define SystemKeyEvent_VK_EXCLAMATION_MARK 517L
#undef SystemKeyEvent_VK_F
#define SystemKeyEvent_VK_F 70L
#undef SystemKeyEvent_VK_F1
#define SystemKeyEvent_VK_F1 112L
#undef SystemKeyEvent_VK_F10
#define SystemKeyEvent_VK_F10 121L
#undef SystemKeyEvent_VK_F11
#define SystemKeyEvent_VK_F11 122L
#undef SystemKeyEvent_VK_F12
#define SystemKeyEvent_VK_F12 123L
#undef SystemKeyEvent_VK_F13
#define SystemKeyEvent_VK_F13 61440L
#undef SystemKeyEvent_VK_F14
#define SystemKeyEvent_VK_F14 61441L
#undef SystemKeyEvent_VK_F15
#define SystemKeyEvent_VK_F15 61442L
#undef SystemKeyEvent_VK_F16
#define SystemKeyEvent_VK_F16 61443L
#undef SystemKeyEvent_VK_F17
#define SystemKeyEvent_VK_F17 61444L
#undef SystemKeyEvent_VK_F18
#define SystemKeyEvent_VK_F18 61445L
#undef SystemKeyEvent_VK_F19
#define SystemKeyEvent_VK_F19 61446L
#undef SystemKeyEvent_VK_F2
#define SystemKeyEvent_VK_F2 113L
#undef SystemKeyEvent_VK_F20
#define SystemKeyEvent_VK_F20 61447L
#undef SystemKeyEvent_VK_F21
#define SystemKeyEvent_VK_F21 61448L
#undef SystemKeyEvent_VK_F22
#define SystemKeyEvent_VK_F22 61449L
#undef SystemKeyEvent_VK_F23
#define SystemKeyEvent_VK_F23 61450L
#undef SystemKeyEvent_VK_F24
#define SystemKeyEvent_VK_F24 61451L
#undef SystemKeyEvent_VK_F3
#define SystemKeyEvent_VK_F3 114L
#undef SystemKeyEvent_VK_F4
#define SystemKeyEvent_VK_F4 115L
#undef SystemKeyEvent_VK_F5
#define SystemKeyEvent_VK_F5 116L
#undef SystemKeyEvent_VK_F6
#define SystemKeyEvent_VK_F6 117L
#undef SystemKeyEvent_VK_F7
#define SystemKeyEvent_VK_F7 118L
#undef SystemKeyEvent_VK_F8
#define SystemKeyEvent_VK_F8 119L
#undef SystemKeyEvent_VK_F9
#define SystemKeyEvent_VK_F9 120L
#undef SystemKeyEvent_VK_FINAL
#define SystemKeyEvent_VK_FINAL 24L
#undef SystemKeyEvent_VK_FIND
#define SystemKeyEvent_VK_FIND 65488L
#undef SystemKeyEvent_VK_FULL_WIDTH
#define SystemKeyEvent_VK_FULL_WIDTH 243L
#undef SystemKeyEvent_VK_G
#define SystemKeyEvent_VK_G 71L
#undef SystemKeyEvent_VK_GREATER
#define SystemKeyEvent_VK_GREATER 160L
#undef SystemKeyEvent_VK_H
#define SystemKeyEvent_VK_H 72L
#undef SystemKeyEvent_VK_HALF_WIDTH
#define SystemKeyEvent_VK_HALF_WIDTH 244L
#undef SystemKeyEvent_VK_HELP
#define SystemKeyEvent_VK_HELP 156L
#undef SystemKeyEvent_VK_HIRAGANA
#define SystemKeyEvent_VK_HIRAGANA 242L
#undef SystemKeyEvent_VK_HOME
#define SystemKeyEvent_VK_HOME 36L
#undef SystemKeyEvent_VK_I
#define SystemKeyEvent_VK_I 73L
#undef SystemKeyEvent_VK_INPUT_METHOD_ON_OFF
#define SystemKeyEvent_VK_INPUT_METHOD_ON_OFF 263L
#undef SystemKeyEvent_VK_INSERT
#define SystemKeyEvent_VK_INSERT 155L
#undef SystemKeyEvent_VK_INVERTED_EXCLAMATION_MARK
#define SystemKeyEvent_VK_INVERTED_EXCLAMATION_MARK 518L
#undef SystemKeyEvent_VK_J
#define SystemKeyEvent_VK_J 74L
#undef SystemKeyEvent_VK_JAPANESE_HIRAGANA
#define SystemKeyEvent_VK_JAPANESE_HIRAGANA 260L
#undef SystemKeyEvent_VK_JAPANESE_KATAKANA
#define SystemKeyEvent_VK_JAPANESE_KATAKANA 259L
#undef SystemKeyEvent_VK_JAPANESE_ROMAN
#define SystemKeyEvent_VK_JAPANESE_ROMAN 261L
#undef SystemKeyEvent_VK_K
#define SystemKeyEvent_VK_K 75L
#undef SystemKeyEvent_VK_KANA
#define SystemKeyEvent_VK_KANA 21L
#undef SystemKeyEvent_VK_KANA_LOCK
#define SystemKeyEvent_VK_KANA_LOCK 262L
#undef SystemKeyEvent_VK_KANJI
#define SystemKeyEvent_VK_KANJI 25L
#undef SystemKeyEvent_VK_KATAKANA
#define SystemKeyEvent_VK_KATAKANA 241L
#undef SystemKeyEvent_VK_KP_DOWN
#define SystemKeyEvent_VK_KP_DOWN 225L
#undef SystemKeyEvent_VK_KP_LEFT
#define SystemKeyEvent_VK_KP_LEFT 226L
#undef SystemKeyEvent_VK_KP_RIGHT
#define SystemKeyEvent_VK_KP_RIGHT 227L
#undef SystemKeyEvent_VK_KP_UP
#define SystemKeyEvent_VK_KP_UP 224L
#undef SystemKeyEvent_VK_L
#define SystemKeyEvent_VK_L 76L
#undef SystemKeyEvent_VK_LEFT
#define SystemKeyEvent_VK_LEFT 37L
#undef SystemKeyEvent_VK_LEFT_PARENTHESIS
#define SystemKeyEvent_VK_LEFT_PARENTHESIS 519L
#undef SystemKeyEvent_VK_LESS
#define SystemKeyEvent_VK_LESS 153L
#undef SystemKeyEvent_VK_M
#define SystemKeyEvent_VK_M 77L
#undef SystemKeyEvent_VK_META
#define SystemKeyEvent_VK_META 157L
#undef SystemKeyEvent_VK_MINUS
#define SystemKeyEvent_VK_MINUS 45L
#undef SystemKeyEvent_VK_MODECHANGE
#define SystemKeyEvent_VK_MODECHANGE 31L
#undef SystemKeyEvent_VK_MULTIPLY
#define SystemKeyEvent_VK_MULTIPLY 106L
#undef SystemKeyEvent_VK_N
#define SystemKeyEvent_VK_N 78L
#undef SystemKeyEvent_VK_NONCONVERT
#define SystemKeyEvent_VK_NONCONVERT 29L
#undef SystemKeyEvent_VK_NUM_LOCK
#define SystemKeyEvent_VK_NUM_LOCK 144L
#undef SystemKeyEvent_VK_NUMBER_SIGN
#define SystemKeyEvent_VK_NUMBER_SIGN 520L
#undef SystemKeyEvent_VK_NUMPAD0
#define SystemKeyEvent_VK_NUMPAD0 96L
#undef SystemKeyEvent_VK_NUMPAD1
#define SystemKeyEvent_VK_NUMPAD1 97L
#undef SystemKeyEvent_VK_NUMPAD2
#define SystemKeyEvent_VK_NUMPAD2 98L
#undef SystemKeyEvent_VK_NUMPAD3
#define SystemKeyEvent_VK_NUMPAD3 99L
#undef SystemKeyEvent_VK_NUMPAD4
#define SystemKeyEvent_VK_NUMPAD4 100L
#undef SystemKeyEvent_VK_NUMPAD5
#define SystemKeyEvent_VK_NUMPAD5 101L
#undef SystemKeyEvent_VK_NUMPAD6
#define SystemKeyEvent_VK_NUMPAD6 102L
#undef SystemKeyEvent_VK_NUMPAD7
#define SystemKeyEvent_VK_NUMPAD7 103L
#undef SystemKeyEvent_VK_NUMPAD8
#define SystemKeyEvent_VK_NUMPAD8 104L
#undef SystemKeyEvent_VK_NUMPAD9
#define SystemKeyEvent_VK_NUMPAD9 105L
#undef SystemKeyEvent_VK_O
#define SystemKeyEvent_VK_O 79L
#undef SystemKeyEvent_VK_OPEN_BRACKET
#define SystemKeyEvent_VK_OPEN_BRACKET 91L
#undef SystemKeyEvent_VK_P
#define SystemKeyEvent_VK_P 80L
#undef SystemKeyEvent_VK_PAGE_DOWN
#define SystemKeyEvent_VK_PAGE_DOWN 34L
#undef SystemKeyEvent_VK_PAGE_UP
#define SystemKeyEvent_VK_PAGE_UP 33L
#undef SystemKeyEvent_VK_PASTE
#define SystemKeyEvent_VK_PASTE 65487L
#undef SystemKeyEvent_VK_PAUSE
#define SystemKeyEvent_VK_PAUSE 19L
#undef SystemKeyEvent_VK_PERIOD
#define SystemKeyEvent_VK_PERIOD 46L
#undef SystemKeyEvent_VK_PLUS
#define SystemKeyEvent_VK_PLUS 521L
#undef SystemKeyEvent_VK_PREVIOUS_CANDIDATE
#define SystemKeyEvent_VK_PREVIOUS_CANDIDATE 257L
#undef SystemKeyEvent_VK_PRINTSCREEN
#define SystemKeyEvent_VK_PRINTSCREEN 154L
#undef SystemKeyEvent_VK_PROPS
#define SystemKeyEvent_VK_PROPS 65482L
#undef SystemKeyEvent_VK_Q
#define SystemKeyEvent_VK_Q 81L
#undef SystemKeyEvent_VK_QUOTE
#define SystemKeyEvent_VK_QUOTE 222L
#undef SystemKeyEvent_VK_QUOTEDBL
#define SystemKeyEvent_VK_QUOTEDBL 152L
#undef SystemKeyEvent_VK_R
#define SystemKeyEvent_VK_R 82L
#undef SystemKeyEvent_VK_RIGHT
#define SystemKeyEvent_VK_RIGHT 39L
#undef SystemKeyEvent_VK_RIGHT_PARENTHESIS
#define SystemKeyEvent_VK_RIGHT_PARENTHESIS 522L
#undef SystemKeyEvent_VK_ROMAN_CHARACTERS
#define SystemKeyEvent_VK_ROMAN_CHARACTERS 245L
#undef SystemKeyEvent_VK_S
#define SystemKeyEvent_VK_S 83L
#undef SystemKeyEvent_VK_SCROLL_LOCK
#define SystemKeyEvent_VK_SCROLL_LOCK 145L
#undef SystemKeyEvent_VK_SEMICOLON
#define SystemKeyEvent_VK_SEMICOLON 59L
#undef SystemKeyEvent_VK_SEPARATER
#define SystemKeyEvent_VK_SEPARATER 108L
#undef SystemKeyEvent_VK_SEPARATOR
#define SystemKeyEvent_VK_SEPARATOR 108L
#undef SystemKeyEvent_VK_SHIFT
#define SystemKeyEvent_VK_SHIFT 16L
#undef SystemKeyEvent_VK_SLASH
#define SystemKeyEvent_VK_SLASH 47L
#undef SystemKeyEvent_VK_SPACE
#define SystemKeyEvent_VK_SPACE 32L
#undef SystemKeyEvent_VK_STOP
#define SystemKeyEvent_VK_STOP 65480L
#undef SystemKeyEvent_VK_SUBTRACT
#define SystemKeyEvent_VK_SUBTRACT 109L
#undef SystemKeyEvent_VK_T
#define SystemKeyEvent_VK_T 84L
#undef SystemKeyEvent_VK_TAB
#define SystemKeyEvent_VK_TAB 9L
#undef SystemKeyEvent_VK_U
#define SystemKeyEvent_VK_U 85L
#undef SystemKeyEvent_VK_UNDEFINED
#define SystemKeyEvent_VK_UNDEFINED 0L
#undef SystemKeyEvent_VK_UNDERSCORE
#define SystemKeyEvent_VK_UNDERSCORE 523L
#undef SystemKeyEvent_VK_UNDO
#define SystemKeyEvent_VK_UNDO 65483L
#undef SystemKeyEvent_VK_UP
#define SystemKeyEvent_VK_UP 38L
#undef SystemKeyEvent_VK_V
#define SystemKeyEvent_VK_V 86L
#undef SystemKeyEvent_VK_W
#define SystemKeyEvent_VK_W 87L
#undef SystemKeyEvent_VK_WINDOWS
#define SystemKeyEvent_VK_WINDOWS 524L
#undef SystemKeyEvent_VK_X
#define SystemKeyEvent_VK_X 88L
#undef SystemKeyEvent_VK_Y
#define SystemKeyEvent_VK_Y 89L
#undef SystemKeyEvent_VK_Z
#define SystemKeyEvent_VK_Z 90L
#ifdef __cplusplus
}
#endif
#endif
