/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WinProcess */

#ifndef _Included_WinProcess
#define _Included_WinProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef WinProcess_SW_HIDE
#define WinProcess_SW_HIDE 0L
#undef WinProcess_SW_MAXIMIZE
#define WinProcess_SW_MAXIMIZE 1L
#undef WinProcess_SW_MINIMIZE
#define WinProcess_SW_MINIMIZE 2L
#undef WinProcess_SW_RESTORE
#define WinProcess_SW_RESTORE 3L
#undef WinProcess_SW_SHOW
#define WinProcess_SW_SHOW 4L
#undef WinProcess_SW_SHOWDEFAULT
#define WinProcess_SW_SHOWDEFAULT 5L
#undef WinProcess_SW_SHOWMAXIMIZED
#define WinProcess_SW_SHOWMAXIMIZED 6L
#undef WinProcess_SW_SHOWMINIMIZED
#define WinProcess_SW_SHOWMINIMIZED 7L
#undef WinProcess_SW_SHOWMINNOACTIVE
#define WinProcess_SW_SHOWMINNOACTIVE 8L
#undef WinProcess_SW_SHOWNA
#define WinProcess_SW_SHOWNA 9L
#undef WinProcess_SW_SHOWNOACTIVATE
#define WinProcess_SW_SHOWNOACTIVATE 10L
#undef WinProcess_SW_SHOWNORMAL
#define WinProcess_SW_SHOWNORMAL 11L
/*
 * Class:     WinProcess
 * Method:    createProcess
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_WinProcess_createProcess__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WinProcess
 * Method:    createProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_WinProcess_createProcess__Ljava_lang_String_2Ljava_lang_String_2ZLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jboolean, jstring);

/*
 * Class:     WinProcess
 * Method:    terminateProcess
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WinProcess_terminateProcess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     WinProcess
 * Method:    executeExe
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_WinProcess_executeExe
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     WinProcess
 * Method:    getValidationCode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_WinProcess_getValidationCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
