/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemEvents */

#ifndef _Included_SystemEvents
#define _Included_SystemEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemEvents
 * Method:    cdRomInsertionRemoval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SystemEvents_cdRomInsertionRemoval
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
