/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WinConsole */

#ifndef _Included_WinConsole
#define _Included_WinConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WinConsole
 * Method:    allocateConsole
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_WinConsole_allocateConsole
  (JNIEnv *, jobject);

/*
 * Class:     WinConsole
 * Method:    getValidationCode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_WinConsole_getValidationCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
