/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileSystemEventManager_NotifyFileSystemListener */

#ifndef _Included_FileSystemEventManager_NotifyFileSystemListener
#define _Included_FileSystemEventManager_NotifyFileSystemListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
