/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileSystemEventManager */

#ifndef _Included_FileSystemEventManager
#define _Included_FileSystemEventManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileSystemEventManager
 * Method:    registerFileSystemListener
 * Signature: (Ljava/lang/String;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_FileSystemEventManager_registerFileSystemListener
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     FileSystemEventManager
 * Method:    unRegisterFileSystemListener
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_FileSystemEventManager_unRegisterFileSystemListener
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
