/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mpeglx */

#ifndef _Included_Mpeglx
#define _Included_Mpeglx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mpeglx
 * Method:    loadMpegLayer3File
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mpeglx_loadMpegLayer3File
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
